## Pre-commit setup

repos:

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--indent=4, --autofix]
        exclude: '.vscode/extensions.json'
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.0'  # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
